astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "OpenAI"
  model_name: "text-embedding-3-small"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  openai:
    provider: "OpenAI"
    type: "ChatOpenAI"
    model_name: "gpt-4o"
    temperature: 0
    max_output_tokens: 2048